# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-15 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BooksReview', '0002_books_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='all_users',
            field=models.ManyToManyField(related_name='all_books', to='BooksReview.users'),
        ),
        migrations.AddField(
            model_name='books',
            name='curr_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='BooksReview.users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='curr_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='BooksReview.books'),
        ),
    ]
