# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-15 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooksReview', '0003_auto_20180915_0142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='books',
            new_name='mybooks',
        ),
    ]
