# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-15 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksReview', '0004_auto_20180915_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybooks',
            name='author',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
