# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-15 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BooksReview', '0005_mybooks_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='all_users',
            field=models.ManyToManyField(related_name='all_reviews', to='BooksReview.users'),
        ),
        migrations.AddField(
            model_name='review',
            name='curr_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='BooksReview.users'),
            preserve_default=False,
        ),
    ]
